# NOTE: make sure to run the metric server

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms3-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms3
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 10
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 10
# setting low to see results
