apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms3
  template:
    metadata:
      labels:
        app: ms3
    spec:
      containers:
        - name: ms3
          image: mayuratverticurl/weatherms3:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "100m" # 100 milliCPU units (half of 200m)
              memory: "128Mi" # 128 Mebibytes (half of 256Mi)
            requests:
              cpu: "50m" # 50 milliCPU units (half of 100m)
              memory: "64Mi" # 64 Mebibytes (half of 128Mi)
          env:
            - name: ms1URL
              value: "http://ms1-service"
            - name: ms2URL
              value: "http://ms2-service"
