apiVersion: v1
kind: Service
metadata:
  name: ms1-service
  namespace: ns3
spec:
  selector:
    app: ms3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
  nodePort: 3000
