apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-service-reader
rules:
  - apiGroups: [""] # "" indicates the core API group
    verbs: ["get", "watch", "list"]
    resources: ["pods", "pods/log", "services"]
    # resourceNames: ["nginx"]
