apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-deployment-read-write-binding
subjects:
  - kind: User
    name: master
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-deployment-read-write
  apiGroup: rbac.authorization.k8s.io
