apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-deployment-read-write
rules:
  - apiGroups: [""]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
    resources: ["pods", "deployments"]
